version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Build started on `date`"
      - cd back-end
      - npm install
      - npm run build
  build:
    commands:
      - cd ..
      - rm -rf libgloss/
      - rm -rf images/
      - mv back-end/* .
      - rm -rf back-end/
      - echo "Build completed on `date`"
      - echo "Creating .env file"
      - touch .env
      - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
      - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
      - echo "AWS_REGION=$AWS_REGION" >> .env

artifacts:
  files:
    - '**/*'