version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Build started on `date`"
      - cd back-end
      - npm build
  build:
    commands:
      - pwd
      - ls
      - cd ..
      - rm -rf libgloss/
      - rm -rf images/
      - mv back-end/* .
      - mv backend/dist/* dist/
      - ls
      - rm -rf back-end/

artifacts:
  files:
    - '**/*'