name: Build android

on:
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Create google services file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON  }}
        run: |
          cd libgloss/android/app/
          touch google-services.json
          echo $DATA > google-services.json
          
      - name: Create empty env file
        run: |
          cd libgloss
          touch .env
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'

      - name: Create build
        env:
          DATA: ${{ GOOGLE_API_KEY }}
        run: |
          cd libgloss
          flutter pub get
          flutter build apk
          flutter build appbundle --dart-define=GOOGLE_API_KEY=$DATA

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ github.workspace }}/libgloss/build/app/outputs/apk/release/app-release.apk
