# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI  

on:
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'

      - name: Create amplifyconfiguration.json
        run: |
          cd libgloss/lib
          touch amplifyconfiguration.json
          echo "${{ secrets.AMPLIFY_CONFIG }}" >> amplifyconfiguration.json

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.18.0

      - name: Install dependencies
        run: |
          cd libgloss
          flutter pub get
          dart analyze
