name: Node.js CI

on:
  push:
    branches-ignore: [ master, development ]
  pull_request:
    branches: [ master, development ]

defaults:
  run:
    working-directory: ./back-end

jobs:
  build:

    runs-on: ubuntu-latest

    environment: libgloss

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_CLUSTER=${{ secrets.DB_CLUSTER }} >> .env
          echo DB_DOMAIN_NAME=${{ secrets.DB_DOMAIN_NAME }} >> .env
          echo SERVICE_ACCOUNT=${{ secrets.SERVICE_ACCOUNT }} >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./back-end/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:integration